### ISSUE TITLE
DropboxOOo authentication error

### ISSUE THREAD

**Issue by JohnEll25** [prrvchr/DropboxOOo#1]
Linux mint  21.1, LibreOffice 7.3.7.2
I have installed DropboxOOo 0.0.6 as detailed in you instructions
When I attempt to authenticate with dropbox through OAuth2OOo 0.0.6 I get an error thrown up (a popup window appears in Chrome) with the message:

This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

Can you help? My dropbox account works fine otherwise (through the Dropbbox app or via my Qnap remote drive connection).
Am I doing something wrong? I would be very grateful for any help as this extension would make my life much easier!
Thanks in anticipation
John Elliott

**Comment by prrvchr** [comment]
Hi John,

Thank you for reporting the problem.

The DropboxOOo application was still in development mode, and we've reached the 500 users limit (I'm glad to know that...)

I just switched it to production mode, we have to wait for Dropbox to agree, I don't know how long it will take...

![dropbox](https://user-images.githubusercontent.com/7834336/235222116-0c6b3812-eb3c-454e-b502-bb2d4cb28ad9.png)

**Comment by JohnEll25** [comment]
HiThat's great to hear. Thanks very much for sorting it. Sent from Samsung Mobile on O2
-------- Original message --------From: prrvchr ***@***.***> Date: 28/04/2023  19:15  (GMT+00:00) To: prrvchr/DropboxOOo ***@***.***> Cc: JohnEll25 ***@***.***>, Author ***@***.***> Subject: Re: [prrvchr/DropboxOOo] DropboxOOo authentication error (Issue #1) 
Hi John,
Thank you for reporting the problem.
The DropboxOOo application was still in development mode, and we've reached the 500 users limit (I'm glad to know that...)
I just switched it to production mode, we have to wait for Dropbox to agree, I don't know how long it will take...

**Comment by prrvchr** [comment]
Ok I close the subject, if ever Dropbox drags too much, let me know I will do the necessary...

**Comment by prrvchr** [comment]
Well apparently it doesn't accept the name, I just renamed the extension to **dbDriverOOo**... We're waiting...

**Comment by JohnEll25** [comment]
Ah, I wondered why it still wasn't authenticating! I dose I need to install the new version(assuming Dropbox accepts the name change)? Thanks for doing this, much appreciated. Sent from Samsung Mobile on O2
-------- Original message --------From: prrvchr ***@***.***> Date: 02/05/2023  03:29  (GMT+00:00) To: prrvchr/dbDriveOOo ***@***.***> Cc: JohnEll25 ***@***.***>, Author ***@***.***> Subject: Re: [prrvchr/dbDriveOOo] DropboxOOo authentication error (Issue #1) 
Well apparently it doesn't accept the name, I just renamed the extension to dbDriverOOo... We're waiting...

**Comment by prrvchr** [comment]
Putting the extension into production may take longer than expected... On the other hand, the current limit is 500 connections. I don't think we've reached that level, so it should work again.

Changes have been made to the **OAuth2OOo** and **dDriveOOo** extensions, please uninstall and reinstall them.
